//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_CertCtrTrx
    {
        public string CertCtrTrxId { get; set; }
        public System.DateTime DhmValue { get; set; }
        public string SiteId { get; set; }
        public string StationNumber { get; set; }
        public string LaneName { get; set; }
        public string BillingId { get; set; }
        public int Gap { get; set; }
        public long pmid { get; set; }
    }
}
