//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_CertTrxLaneInterface
    {
        public System.DateTime DhmValue { get; set; }
        public string SiteId { get; set; }
        public string StationNumber { get; set; }
        public string LaneName { get; set; }
        public int TrxNumber { get; set; }
        public int TrxIndex { get; set; }
        public string BillingId { get; set; }
        public double PartialPrice { get; set; }
        public string OctalCode { get; set; }
        public string ModeId { get; set; }
        public bool IsChecked { get; set; }
        public bool IsZip { get; set; }
        public bool IsCe { get; set; }
        public string CategoryPreDacId { get; set; }
        public string StationNumberO { get; set; }
        public int CertTrxLaneInterfaceRowId { get; set; }
        public bool IsLane { get; set; }
        public bool IsMsg { get; set; }
        public string PostNumber { get; set; }
        public string LaneTypeId { get; set; }
        public bool IsLS { get; set; }
    
        public virtual dt_QualifTrxLane dt_QualifTrxLane { get; set; }
    }
}
