//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_HomeUpdateEdit
    {
        public int HomeUpdateEditId { get; set; }
        public int HomeUpdateId { get; set; }
        public string UserId { get; set; }
        public System.DateTime DhmModification { get; set; }
        public string Response { get; set; }
        public System.DateTime DhmValueStart { get; set; }
        public System.DateTime DhmValueEnd { get; set; }
        public double Duration { get; set; }
        public string ImageExtension { get; set; }
        public string Link { get; set; }
    }
}
