//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_HomeUpdate
    {
        public int HomeUpdateId { get; set; }
        public string UpdateMessage { get; set; }
        public string UserId { get; set; }
        public string UpdateStatusId { get; set; }
        public System.DateTime DhmValue { get; set; }
        public string Response { get; set; }
        public string EmergencyId { get; set; }
        public int HomeUpdateEditId { get; set; }
        public int PluginId { get; set; }
        public int IdParent { get; set; }
        public string ChannelId { get; set; }
        public System.DateTime DhmPlan { get; set; }
        public int TeamId { get; set; }
        public int RowOrder { get; set; }
        public int VersionId { get; set; }
        public string HandledBy { get; set; }
    
        public virtual dt_CommVersions dt_CommVersions { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
