//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_Mp
    {
        public string MpId { get; set; }
        public string MpName { get; set; }
        public string MpNameOpe { get; set; }
        public string MpNameCe { get; set; }
        public string MpAcronym { get; set; }
        public bool IsActive { get; set; }
        public string MpCategory { get; set; }
        public string MpGroup { get; set; }
        public string MpNameExpert { get; set; }
        public int MpOrderExpert { get; set; }
        public string MpCategoryExpert { get; set; }
    }
}
