//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_ParamCategories
    {
        public string CategoryId { get; set; }
        public string CategoryName { get; set; }
        public int AxleNumber { get; set; }
        public bool IsHeight { get; set; }
    }
}
