//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_Profils
    {
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public long pmid { get; set; }
        public string LastName { get; set; }
        public string IpNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string SiteId { get; set; }
        public string Stations { get; set; }
        public string Emailcc { get; set; }
        public string ChromePath { get; set; }
        public string CeUserName { get; set; }
        public string CePassword { get; set; }
        public bool IsConnected { get; set; }
        public bool IsImage { get; set; }
        public bool IsReportReceipt { get; set; }
        public bool IsReportPost { get; set; }
        public bool IsReportNr { get; set; }
        public bool IsReportTrafic { get; set; }
        public bool IsReportVers { get; set; }
        public bool IsReportTrxLane { get; set; }
        public string LSIds { get; set; }
        public string ImageExtension { get; set; }
        public string Address { get; set; }
        public System.DateTime Birthday { get; set; }
        public bool IsMale { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public bool IsNotificationActive { get; set; }
        public bool IsDefaultMode { get; set; }
        public string PhoneFix { get; set; }
        public string RegionIds { get; set; }
        public string ZoneLevelIds { get; set; }
        public string TimeLevelIds { get; set; }
        public string CexIds { get; set; }
        public string Email { get; set; }
        public string JobCode { get; set; }
        public string NetworkIds { get; set; }
        public string AxleIds { get; set; }
        public string CellIds { get; set; }
    }
}
