//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_ParamUpdateStatus
    {
        public string UpdateStatusId { get; set; }
        public string UpdateStatusName { get; set; }
        public long pmid { get; set; }
        public string RgbValue { get; set; }
        public string ProgressValue { get; set; }
        public int Order { get; set; }
        public string StatusTypeId { get; set; }
    }
}
