//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_ParamLanes
    {
        public string SiteId { get; set; }
        public string StationNumber { get; set; }
        public string LaneName { get; set; }
        public string IpAddress { get; set; }
        public string LaneTypeId { get; set; }
        public bool IsTest { get; set; }
        public int Rayon { get; set; }
        public bool IsCamContext { get; set; }
        public bool IsCamIapi { get; set; }
        public int PurgeDuration { get; set; }
        public bool IsHms { get; set; }
        public bool IsWriteTime { get; set; }
        public bool IsTrxNumber { get; set; }
        public bool IsLicensePlate { get; set; }
        public int CamBrandId { get; set; }
        public string LaneModeName { get; set; }
        public string CamBrandName { get; set; }
        public string CamModelName { get; set; }
        public string CamRefName { get; set; }
        public string CamIpAddress { get; set; }
        public string Observation { get; set; }
        public string CamIapiIpAddress { get; set; }
        public string ImageTypeId { get; set; }
        public int ImagesNumber { get; set; }
        public bool IsNoneStop { get; set; }
        public bool IsActive { get; set; }
        public bool IsCyclopeNewtrip { get; set; }
        public int LaneId { get; set; }
        public bool IsPing { get; set; }
        public string PingComment { get; set; }
        public System.DateTime DhmValuePing { get; set; }
        public bool IsInverted { get; set; }
        public bool IsCalculateOnContext { get; set; }
        public bool IsChecked { get; set; }
        public bool IsAssigned { get; set; }
        public string AccessComment { get; set; }
    }
}
