//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_ParamThreads
    {
        public int CertFilePlanId { get; set; }
        public bool IsFinnished { get; set; }
        public long pmid { get; set; }
        public string CertFileIdHeader { get; set; }
        public System.DateTime DhmCreation { get; set; }
    }
}
