//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_QualifTrxLane
    {
        public int QualifTrxLaneRowId { get; set; }
        public string CategoryPostDacId { get; set; }
        public string ProductNumber { get; set; }
        public string ReadTickNumber { get; set; }
        public System.DateTime DhmValueO { get; set; }
        public string LaneNameO { get; set; }
        public string ObsPassId { get; set; }
        public string ObsTickId { get; set; }
        public string ObsMpId { get; set; }
        public bool IsPathQualified { get; set; }
        public string NetworkId { get; set; }
        public string NetworkIdO { get; set; }
        public bool IsConvenientContext { get; set; }
        public bool IsConvenientIapi { get; set; }
        public bool IsConvenientClass { get; set; }
        public bool IsConvenientContextO { get; set; }
        public bool IsConvenientIapiO { get; set; }
        public string ObsSequId { get; set; }
        public string ObsOcrId { get; set; }
        public string SerialNumber { get; set; }
        public string CashierNumber { get; set; }
        public double Speed { get; set; }
        public string LicensePlate { get; set; }
        public string LicensePlateO { get; set; }
        public bool IsPathQualifiedObsTickIdD { get; set; }
    
        public virtual dt_CertTrxLaneInterface dt_CertTrxLaneInterface { get; set; }
    }
}
