//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_Stations
    {
        public string NetworkId { get; set; }
        public string SiteId { get; set; }
        public string StationNumber { get; set; }
        public string StationName { get; set; }
        public string BagHeader { get; set; }
        public string BagContainerId { get; set; }
        public string LSId { get; set; }
        public string StationOpeName { get; set; }
        public string StationCeName { get; set; }
        public string StationCeNumber { get; set; }
        public bool IsDouble { get; set; }
        public int LanesNumber { get; set; }
        public bool IsPdv { get; set; }
        public string CexIdCe { get; set; }
        public string StationIdCe { get; set; }
        public bool IsVirtual { get; set; }
        public string SiteIdCe { get; set; }
        public int SearchLatency { get; set; }
        public int ExportLatency { get; set; }
        public string BagContainerIdCe { get; set; }
        public string Sens { get; set; }
        public string StationNameOpeTrafic { get; set; }
        public string StationNameOpeReceipt { get; set; }
        public string StationNameOpeNr { get; set; }
        public string StationNameOpePost { get; set; }
        public string SectionId { get; set; }
        public string AxleId { get; set; }
        public string CexId { get; set; }
        public string DivisionId { get; set; }
        public int OrderNumber { get; set; }
        public string System { get; set; }
        public string BagContainerName { get; set; }
        public bool IsPrincipal { get; set; }
        public bool IsBidirectional { get; set; }
        public int PK { get; set; }
        public string Color { get; set; }
        public int StationOdIndex { get; set; }
        public bool IsActive { get; set; }
        public int TmjLastMonth { get; set; }
        public double RmjLastMonth { get; set; }
        public double ReceiptTlpRateLastMonth { get; set; }
        public double NumberTlpRateLastMonth { get; set; }
        public int StationId { get; set; }
        public int SectionOrder { get; set; }
        public bool IsSwitch { get; set; }
        public int SectionOrder1 { get; set; }
        public int SectionOrder2 { get; set; }
        public int SectionOrder0 { get; set; }
        public bool IsImage { get; set; }
        public bool IsLoyalty { get; set; }
        public bool IsRealTime { get; set; }
        public string RegionId { get; set; }
        public bool IsCyclopeMatching { get; set; }
        public bool IsCyclopeClassify { get; set; }
        public string CellId { get; set; }
        public string AxleIdExpert { get; set; }
        public Nullable<int> PK2 { get; set; }
        public string StationNameExpert { get; set; }
    }
}
