//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_Sites
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dt_Sites()
        {
            this.dt_LS = new HashSet<dt_LS>();
        }
    
        public string SiteId { get; set; }
        public string SiteName { get; set; }
        public int StationsNumber { get; set; }
        public int SensesNumber { get; set; }
        public int BagContainerNumber { get; set; }
        public int LanesNumber { get; set; }
        public int PdvsNumber { get; set; }
        public int PdvPostsNumber { get; set; }
        public string SiteIdCe { get; set; }
        public bool IsVirtual { get; set; }
        public string AxleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dt_LS> dt_LS { get; set; }
    }
}
