//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_TeamMembers
    {
        public int TeamMemberId { get; set; }
        public System.DateTime DhmCreation { get; set; }
        public System.DateTime DhmModification { get; set; }
        public int TeamId { get; set; }
        public string MemberId { get; set; }
    }
}
