//Param
ParamFileTypeGet





//Fdr
RepoFdrHomeOpen

RepoFdrAddOpen
RepoFdrAdd
RepoFdrThSave
RepoFdrSumUpdate

RepoFdrAdd
RepoFdrAddFormLoad

RepoFdrEditSave
RepoFdrEditModify
RepoFdrEditFormOnClickGet
RepoFdrEditFormLoad
RepoFdrEditAdd

//Certification
CertAllReportsHide
CertAllParametersHide
CertLaneHomeOpen

//CertRealMenu
CertRealHomeOpen

CertRealTrxOpen
CertRealTrxAllDisplay
CertRealTrxDayDisplay
CertRealTrxDayGet
CertRealTrxStationDisplay
CertRealTrxStationGet
CertRealTrxHourDisplay
CertRealTrxHourSearch
CertRealTrxHourGet
CertRealTrxLaneDisplay
CertRealTrxLaneSearch
CertRealTrxLaneGet
CertTrxLaneSearch

CertReceiptBagSearch

CertRealImageOpen
CertRealImageAllDisplay
CertRealImageDayDisplay
CertRealImageDayGet
CertRealImageStationDisplay
CertRealImageStationGet
CertRealImageHourDisplay
CertRealImageHourSearch
CertRealImageHourGet
CertRealImageLaneDisplay
CertRealImageLaneSearch
CertRealImageLaneGet

//Acc
AccProfilEdit

//Od
OdHomeOpen
OdTraficHomeOpen
OdAllParametersHide
OdAllReportsHide


OdTraficPresetGet

OdTraficOdDayOpen
OdTraficMatriceOpen
OdTraficMatriceDayOpen
OdTraficMatriceCumulOpen


OdTraficPresetGet
RepoTraficStationDayDisplay
RepoTraficRevenueStationDayGet

OdTraficPreview

OdTraficOpen
OdTraficSectionUpdate
OdTraficSectionCumulOpen
OdTraficScopeCumulOpen
OdTraficSectionCumulDisplay
OdTraficSectionCumulGet
OdTraficOdSectionSearch


OdTraficOdCumulDisplay
OdTraficOdCumulFromMatriceSearch
OdTraficOdCumulFromSectionSearch
OdTraficOdCumulGet
OdTraficOdDayFromMatriceGet

OdTraficOdDayDisplay
OdTraficOdDaySearch
OdTraficOdDayGet
OdTraficOdDayFromMatriceGet

OdTraficNrDaySearch
OdTraficNrDayGet

OdTraficMatriceOdDayDisplay
OdTraficMatriceOdCumulDisplay
OdTraficMatriceOdCumulGet
OdTraficMatriceOdCumulA1Get
OdTraficMatriceOdCumulA2Get
OdTraficMatriceOdCumulA3Get
OdTraficMatriceOdCumulA4Get
OdTraficMatriceOdCumulA5Get

OdTraficMatriceCumulPreview
OdTraficMatriceCumulNotify

OdMatriceGet
OdMatriceA1Get
OdMatriceA2Get
OdMatriceA3Get
OdMatriceA4Get
OdMatriceA5Get
OdMatriceMeanValueUpdate

OdAllDisplay



Export
RepoTraficOdGet
RepoTraficOdOpeUpload
ParamCertAxlesGet
ActionBtnMarginSpin
RepoTraficOdAllReportsHide

Export

BiColumnGet
BiColumnFormLoad
RepoFdrAdd

//CertTrafic
CertTraficHomeOpen

CertTraficSectionDayGet


CertTraficHourOpen
CertTraficHourAllDisplay
CertTraficHourDayDisplay
CertTraficHourDayHandle
CertTraficHourDayGet
CertTraficHourStationDisplay
CertTraficHourStationSearch
CertTraficHourStationGet
CertTraficHourLaneDisplay
CertTraficHourLaneSearch
CertTraficHourLaneGet

CertDayDisplay
CertTraficSectionSearch
CertTraficSectionGet
CertTraficOdSearch
CertRecoDataSearch
CertTrxLaneLaneReceiptSearch
CertRecoDataSearch

CertTraficOdDayGet
CertTraficOdStationSearch
CertTraficOdStationGet
CertTraficOdGet
CertTraficOdTrxLaneGet

QualifTrxLaneDisplay
QualifTrxLaneGet
QualifTrxLaneSearch

RepoTraficOdTrxLaneMatriceOpen

RepoTraficOdHomeOpen

RepoPrint


//Reporting
CertReportingTraficDayGet

CertReportingTraficStationDisplay
CertReportingTraficStationSearch
CertReportingTraficStationGet
CertReportingTraficBillingSearch
CertReportingTraficBillingGet
CertReportingTraficLaneSearch
CertReportingTraficLaneGet
CertReportingTraficHourSearch
CertReportingTraficHourGet







BiAttributeGet


//QualifMenu
QualifAllReportsHide
QualifAllParametersHide
QualifLaneHomeOpen

QualifNotify
QualifPreview

QualifQualifHomeOpen
QualifSearchHomeOpen
QualifPathOpen
QualifPathDisplay
QualifPathSearch
QualifPathGet
QualifPathFormLoad
QualifPathEdit

QualifTrxLaneOpen
QualifTrxLaneDisplay
QualifTrxLaneUpload
QualifTrxLaneImageUpload

QualifTrxBorneOpen


QualifMatchingCyclopeFormGet
QualifMatchingAdmFormGet
QualifAdmIdEdit
QualifPathCarouselDisplay
QualifPathCarouselGet
QualifPathAxlesNumberEdit
QualifPathLabelFormGet
QualifPathAxleFormGet
QualifPathExpertCategoryIdEdit
QualifPathSeniorCategoryIdEdit

QualifQualifHomeOpen

QualifDashOpen
QualifDashNotify

QualifRobotOpen
QualifRobotDisplay
QualifRobotGet

QualifPlanOpen
QualifPlanDisplay
QualifPlanGet
QualifPlanAdd


QualifTrxLaneAllDisplay
QualifTrxLaneDayDisplay
QualifTrxLaneDayGet
QualifTrxLaneRegionDisplay
QualifTrxLaneRegionSearch
QualifTrxLaneRegionGet
QualifTrxLaneStationDisplay
QualifTrxLaneStationSearch
QualifTrxLaneStationGet
QualifTrxLaneOdDisplay
QualifTrxLaneOdSearch
QualifTrxLaneOdGet
QualifTrxLaneLaneDisplay
QualifTrxLaneLaneSearch
QualifTrxLaneLaneGet
QualifTrxLaneHourGet
QualifTrxLaneSearch
QualifTrxLaneGet
QualifTrxLaneFromOdSearch
QualifTrxLaneIsConvenientContextSet
QualifTrxLaneStationExport
QualifTrxLaneDisplay
QualifTrxLaneImageUpload
CertImageFromLaneUpload

QualifObsMpOpen
QualifObsMpAllDisplay
QualifObsMpDayDisplay
QualifObsMpDayGet
QualifObsMpRegionDisplay
QualifObsMpRegionSearch
QualifObsMpRegionGet
QualifObsMpStationDisplay
QualifObsMpStationSearch
QualifObsMpStationGet
QualifObsMpOdDisplay
QualifObsMpOdSearch
QualifObsMpOdGet
QualifObsMpLaneDisplay
QualifObsMpLaneSearch
QualifObsMpLaneGet

QualifObsPassOpen
QualifObsPassAllDisplay
QualifObsPassDayDisplay
QualifObsPassDayGet
QualifObsPassRegionDisplay
QualifObsPassRegionSearch
QualifObsPassRegionGet
QualifObsPassStationDisplay
QualifObsPassStationSearch
QualifObsPassStationGet
QualifObsPassOdDisplay
QualifObsPassOdSearch
QualifObsPassOdGet
QualifObsPassLaneDisplay
QualifObsPassLaneSearch


QualifExportOpen



QualifAnalyticHomeOpen


QualifQualifHomeOpen
QualifObsTickIdPOpen

QualifObsTickIdPAllDisplay
QualifObsTickIdPDayDisplay
QualifObsTickIdPDayGet
QualifObsTickIdPRegionDisplay
QualifObsTickIdPRegionSearch
QualifObsTickIdPRegionGet
QualifObsTickIdPStationDisplay
QualifObsTickIdPStationSearch
QualifObsTickIdPStationGet

QualifExport
QualifObsTickIdDOpen
QualifObsTickIdDPresetGet

QualifObsTickIdDScopeCumulOpen
QualifObsTickIdDScopeCumulDisplay
QualifObsTickIdDScopeCumulGet

QualifObsTickIdDAllDayOpen
QualifObsTickIdDAllDayDisplay
QualifObsTickIdDAllDayGet

QualifObsTickIdDRegionDayOpen
QualifObsTickIdDRegionDayDisplay
QualifObsTickIdDRegionDaySearch
QualifObsTickIdDRegionDayGet

QualifObsTickIdDStationDayOpen
QualifObsTickIdDStationDayDisplay
QualifObsTickIdDStationDaySearch
QualifObsTickIdDStationDayGet

QualifObsTickIdDLaneDayOpen
QualifObsTickIdDLaneDayDisplay
QualifObsTickIdDLaneDaySearch
QualifObsTickIdDLaneDayGet

QualifObsTickIdDTableExport


QualifObsTickIdPPerfOpen
QualifObsTickIdPPerfAllDisplay
QualifObsTickIdPPerfDayDisplay
QualifObsTickIdPPerfDayGet
QualifObsTickIdPPerfCumulDisplay
QualifObsTickIdPPerfCumulGet

QualifPerfLabelOpen
QualifPerfLabelGet

QualifObsTickIdDPerfOpen
QualifObsTickIdDPerfAllDisplay
QualifObsTickIdDPerfDayDisplay
QualifObsTickIdDPerfDayGet
QualifObsTickIdDPerfCumulDisplay
QualifObsTickIdDPerfCumulGet

DataTableIntOnClickGet

QualifCashOpen

QualifSearchHomeOpen
QualifSearchObsTickIdPOpen
QualifSearchObsMpId26Open


QualifTrxLaneJs
QualifSearchRepeatByTagOpen
QualifSearchRepeatByTagDisplay
QualifSearchRepeatByTagGet
QualifSearchRepeatByTagExport
QualifSearchRepeatByTagInsightGet
QualifSearchRepeatByTagFormLoad
QualifSearchRepeatByTagEdit
QualifSearchRepeatByTagReportGet
QualifSearchRepeatPathGet
ParamProductUpdate

QualifSearchRepeatByPlateOpen
QualifSearchRepeatByPlateDisplay
QualifSearchRepeatByPlateGet
QualifSearchRepeatByPlateInsightGet

QualifSearchRepeatPathGet

QualifSearchRepeatByTagFormSearch

QualifPathDisplay
QualifPathBySerialNumberSearch
QualifPathBySerialNumberGet
QualifPathRealTimeDisplay
QualifPathRealTimeGet
QualifInsightDisplay
QualifObsTickIdPDayInsightGet
QualifObsTickIdDDayInsightGet
TopBarFixInsightDisplay
TopBarHistoryInsightGet
QualifSearchRepeatByTagInsightGet
QualifSearchRepeatByPlateInsightGet

QualifPortailObsTickIdDOpen
QualifMinuteDisplay
QualifMinuteGet
QualifTpdMinuteExport

//Disc
DiscAllReportsHide
DiscAllParametersHide
DiscHomeOpen
DiscOpen
DiscAllDisplay
DiscDayDisplay
DiscDayGet
DiscRegionSearch
DiscRegionGet
DiscStationDisplay
DiscStationSearch
DiscStationGet
DiscLaneDisplay
DiscLaneSearch
DiscLaneGet
DiscSearch
DiscGet
DiscDayDisplay
DiscRequestNotify

DiscStationDisplay
DiscOpen
DiscStationDisplay
DiscDayGet

DiscAnalyticHomeOpen
DiscAnalyticOpen
DiscPresetGet
DiscAllDisplay

DiscGlobalDayOpen
DiscGlobalDayDisplay
DiscGlobalDayGet

DiscScopeCumulOpen
DiscScopeCumulDisplay
DiscScopeCumulGet

DiscGlobalDayOpen
DiscTableExport

DiscPreview
DiscNotify
QualifNotify


ParamTimesOnChangeGet


CertTrxLaneFullDayGet
CertTrxLaneFullStationSearch
CertTrxLaneFullStationGet
CertTrxLaneFullLaneSearch
CertTrxLaneFullLaneGet
CertTrxLaneFullHourSearch

CertTrxLaneOpen

ParamPresetsGet
ParamLanesGet
ParamGetStations
ParamSectionFromAxleSecGet

CertImageHomeOpen
CertTrxLaneFullOpen
CertTrxLaneFullDayGet
CertTrxLaneDayGet
CertTrxLaneFullLaneSearch

CertImageLaneOpen
CertImageBorneOpen
CertTrxLaneFullStationGet

CertDayDisplay

//CertTrxLaneLeap
CertTrxLaneLeapOpen
CertTrxLaneLeapAllDisplay
CertTrxLaneLeapDayDisplay
CertTrxLaneLeapDayGet

CertTrxLaneLeapStationDisplay
CertTrxLaneLeapStationSearch
CertTrxLaneLeapStationGet

CertTrxLaneLeapSearch
CertTrxLaneLeapGet
CertTrxLaneLeapPathSearch


//CertImageLane
CertImageLaneDayGet
CertImageLaneLsSearch
CertImageLaneLsDisplay
CertImageLaneLsGet
CertImageLaneStationDisplay
CertImageLaneStationSearch
CertImageLaneStationGet

CertImageLaneLaneDisplay
CertImageLaneLaneSearch
CertImageLaneLaneGet


CertImageLaneHourSearch
CertImageLaneHourGet

CertImageLaneHistorySearch
CertImageLaneHistoryGet

CertImageTrxLaneSearch
CertImageTrxBorneSearch
CertImageBorneOpen
CertImageBorneDayGet



//
CertBiHomeOpen






CertLoyHomeOpen
CertLoyOccOpen
CertDayDisplay

CertLoyTrxLaneDayGet


QualifOccDisplay
QualifOccOpen
QualifOccGet


//Loy
LoyOccSearch


LoyOccLabelSearch



CertTrxLaneOpen

CertLoyOccOpen
CertDayDisplay



CertRecoDataFromStationSearch
ParamLSFromCexGet
ParamLSSecGet

//Cert
CertTrxLaneOpen
CertTrxLaneSearch
CertTrxLaneStationDisplay
CertTrxLaneStationSearch
CertTrxLaneStationGet
CertTrxLaneStationDisplay
CertTrxLaneLaneGet
CertTrxLaneLaneSearch
CertTrxLaneLaneReceiptSearch
CertTrxLaneLaneReceiptGet
CertTrxLaneHourGet
CertTrxLaneHourSearch
CertTrxLaneLaneReceiptSearch
CertTrxLaneHourReceiptSearch

CertTrxLaneFullStationSearch
CertTrxLaneFullStationGet

//CertTrxBorne
CertTrxBorneOpen
CertTrxBorneAllDisplay

CertTrxBorneDayDisplay
CertTrxBorneDayGet

CertTrxBorneStationDisplay
CertTrxBorneStationSearch
CertTrxBorneStationGet

CertTrxBorneBorneDisplay
CertTrxBorneBorneSearch
CertTrxBorneBorneGet

CertTrxBorneHourSearch
CertTrxBorneHourGet

CertTrxBorneOpen
CertTrxBorneSearch
CertTrxBorneGet







ParamGetSites

ParamAxlesGet







CertRecoDataSearch

DataTableCheckBoxGet

//Repo
RepoHomeOpen

RepoTraficStationAllReportsHide();
RepoTraficStationAllParamsHide();

RepoTraficHomeOpen

RepoTraficStationHourOpen
RepoTraficStationHourDisplay
RepoTraficStationHourGet
RepoTraficRevenueStationDayAllMeNotify
RepoTraficRevenueStationDayAllDgNotify

RepoTraficStationDayOpen
RepoTraficStationDayDisplay
RepoTraficStationDayGet

RepoTraficAllDayOpen
RepoTraficAllDayDisplay
RepoTraficAllDayGet

RepoTraficAllMonthOpen
RepoTraficAllMonthDisplay
RepoTraficAllMonthGet

RepoTraficAllCumulOpen
RepoTraficAllCumulDisplay
RepoTraficAllCumulGet

RepoTraficAllYearOpen
RepoTraficAllYearDisplay
RepoTraficAllYearGet

RepoTraficAllYearCgOpen
RepoTraficAllYearCgDisplay
RepoTraficAllYearCgGet


RepoTraficRegionCumulOpen
RepoTraficRegionCumulDisplay
RepoTraficRegionCumulGet

RepoTraficScopeCumulOpen
RepoTraficScopeCumulDisplay
RepoTraficScopeCumulGet

RepoTraficStationCumulOpen
RepoTraficStationCumulDisplay
RepoTraficStationCumulGet


RepoTraficPresetGet

RepoRevenueHomeOpen

RepoRevenueStationDayOpen
RepoRevenueStationDayDisplay
RepoRevenueStationDayGet

RepoRevenueAllDayOpen
RepoRevenueAllDayDisplay
RepoRevenueAllDayGet

RepoRevenueAllMonthOpen
RepoRevenueAllMonthDisplay
RepoRevenueAllMonthGet

RepoRevenueAllCumulOpen
RepoRevenueAllCumulDisplay
RepoRevenueAllCumulGet

RepoRevenueAllYearOpen
RepoRevenueAllYearDisplay
RepoRevenueAllYearGet

RepoRevenueAllYearCgOpen
RepoRevenueAllYearCgDisplay
RepoRevenueAllYearCgGet

RepoRevenuePresetGet
RepoNotify
RepoPreview

DataTableFormatRateGet
DataTablePercentageGet
DataTableFormatIntDividedGet


QualifLoyHomeOpen
ParamPresetsGet

SaeRdtDisplay
SaeRdtGet
SaeRdtAdd
SaeSensorGet
SaeSensorAdd


CertDayDisplay
CertImageLaneOpen
CertImageLaneAllDisplay
CertImageLaneDayDisplay
CertImageLaneDayGet
CertImageLaneStationGet
CertImageLaneLaneDisplay
CertImageLaneLaneGet
CertImageLaneLaneSearch
CertImageLaneHourGet

//CertEventMenu<
CertEventHomeOpen
CertIsValidGet

CertEventOpen
CertEventAllDisplay
CertEventDayDisplay
CertEventDayGet
CertEventStationDisplay
CertEventStationSearch
CertEventStationGet
CertEventLaneDisplay
CertEventLaneGet
CertEventLaneSearch
CertEventSearch
CertEventGet

CertBreachOpen
CertBreachAllDisplay
CertBreachDayDisplay
CertBreachDayGet
CertBreachStationDisplay
CertBreachStationSearch
CertBreachStationGet
CertBreachLaneDisplay
CertBreachLaneSearch
CertBreachLaneGet
CertBreachSearch
CertBreachGet

CertMinuteOpen
CertMinuteAllDisplay
CertMinuteDayDisplay
CertMinuteDayGet
CertMinuteStationDisplay
CertMinuteStationSearch
CertMinuteStationGet
CertMinuteLaneDisplay
CertMinuteLaneSearch
CertMinuteLaneGet
CertMinuteSearch
CertMinuteGet

CertMinuteHandleOpen
CertMinuteHandleAllDisplay
CertMinuteHandleDayDisplay
CertMinuteHandleDayGet
CertMinuteHandleStationDisplay
CertMinuteHandleStationSearch
CertMinuteHandleStationGet
CertMinuteHandleLaneDisplay
CertMinuteHandleLaneSearch
CertMinuteHandleLaneGet

CertCrmOpen
CertCrmAllDisplay
CertCrmDayDisplay
CertCrmDayGet
CertBreachStationDisplay
CertBreachStationSearch
CertBreachStationGet
CertBreachLaneDisplay
CertBreachLaneSearch
CertBreachLaneGet
CertBreachSearch
CertBreachGet

CertDiscOpen
CertDiscAllDisplay
CertDiscDayDisplay
CertDiscDayGet
CertDiscStationDisplay
CertDiscStationSearch
CertDiscStationGet
CertBreachLaneDisplay
CertBreachLaneSearch
CertBreachLaneGet
CertBreachSearch
CertBreachGet

//Breach
BreachAllReportsHide
BreachAllParametersHide
BreachHomeOpen

BreachSearch
BreachSearchOpen

BreachListOpen
BreachListDisplay
BreachListSearch
BreachListGet
BreachMinuteExport

BreachRepeatOpen
BreachRepeatDisplay
BreachRepeatGet
BreachRepeatFormLoad
BreachRepeatHandleGet

BreachPlateOpen
BreachPlateDisplay
BreachPlateGet

BreachDashOpen
BreachPresetGet
BreachPreview
BreachNotify

BreachScopeCumulOpen
BreachScopeCumulDisplay
BreachScopeCumulGet



SaeEquipmentHomeOpen
SaeSiteGet
SaeEquipmentDisplay
SaeEquipmentGet
SaeEquipmentAdd
SaeRdtAdd

SaeTraficOpen
SaeTraficDayDisplay
SaeTraficDayGet
SaeTraficAxleSearch
SaeTraficAxleGet
SaeTraficRdtSearch
SaeTraficRdtGet
SaeTraficMeasureSearch
SaeTraficMeasureGet
SaeTraficSensorSearch
SaeTraficHourSearch
SaeTraficMinuteSearch
SaeTraficMi

NotiConnectionIdUpdate
CertTaskAdd

CertTaskVisualizeMsgGet
CertTaskVisualizeZipGet



ParamSiteFromAxleSecGet

ParamTimesGet
ParamTitleSet
ParamSiteFromAxleSecGet
ParamBagContainersFromLSGet

ParamSiteFromAxleSecGet
ParamSiteFromAxleSecGet

RepoTraficRevenueStationDayAllNotify

DataTableIsValidSwitch
ElementIfExistsCheck

QualifDashOpen

//Qualif
ParamPresetsGet

QualifPathOpen
QualifPathDisplay
QualifPathGet
QualifPathEdit
QualifPathExport
QualifPathFormLoad

QualifTrxLaneOpen
QualifTrxLaneGet
QualifTrxLaneSearch
QualifTrxLaneDayDisplay
QualifTrxLaneStationGet

CertImageRestaure
CertImageUpload
CertImageFrom23Upload
CertImageFrom165Upload
CertImageFromBackupUpload


CertImageHomeOpen
CertImageLaneOpen
CertImageLaneLaneSearch
CertTrxLaneFullOpen
QualifTrxLaneDayDisplay
QualifTrxLaneDayGet
QualifTrxLaneStationSearch
QualifTrxLaneStationGet
QualifTrxLaneLaneSearch
QualifTrxLaneLaneGet
QualifTrxLaneSearch
QualifTrxLaneNotify


QualifTrxLaneGet
QualifPathFormLoad
QualifPathEdit
QualifPathGet
QualifPathLogsGet
QualifPathRequestsGet
QualifPathOpeGet
QualifPathByLicensePlateSearch
QualifPathByLicensePlateGet
QualifPathBySerialNumberSearch
QualifPathBySerialNumberGet

QualifTrxBorneOpen
QualifTrxBorneDisplay
QualifTrxBorneGet


QualifOccDisplay
QualifOccGet
QualifTrxLaneOpen

QualifDashOpen
QualifObsTickTimePresetGet
QualifObsTickIdDOpen
QualifObsTickIdDAllDayOpen
QualifObsTickIdDAllDayDisplay
QualifObsTickIdDAllDayGet

QualifObsTickIdDRegionDayOpen
QualifObsTickIdDRegionDayDisplay
QualifObsTickIdDRegionDaySearch
QualifObsTickIdDRegionDayGet

QualifObsTickIdDStationDayOpen
QualifObsTickIdDStationDayDisplay
QualifObsTickIdDStationDaySearch
QualifObsTickIdDStationDayGet

QualifObsTickIdDLaneDayOpen
QualifObsTickIdDLaneDayDisplay
QualifObsTickIdDLaneDaySearch
QualifObsTickIdDLaneDayGet

QualifTrxLaneAllDisplay
QualifTrxLaneDayDisplay
QualifTrxLaneStationDisplay
QualifTrxLaneStationSearch
QualifTrxLaneStationGet
QualifTrxLaneLaneGet
QualifTrxLaneStationSearch
QualifTrxLaneSearch


QualifPathOpen
QualifPathGet
QualifPathSearch

QualifDashOpen
QualifDashNotify
QualifTimePreset



QualifTrxBorneByLicensePlateSearch
QualifTrxBorneBySerialNumberSearch
QualifTrxBorneBySerialNumberGet
QualifPathLogsIsValidSwitch
QualifTrxLaneAllDisplay
DataTableIsValidSwitch
QualifTrxLaneOpen

QualifTimePreset

QualifPathOpeGet

QualifSearchRepeatByTagFormSearch
QualifSearchRepeatByPlateFormSearch

QualifSearchRepeatByTagFormView
QualifSearchRepeatByPlateFormView

CertImageFromLaneUpload
CertImageFrom165Upload
CertImageFrom23Upload
CertImageRestaure

CertImageBorneFromBorneUpload
Export
ParamGetBagContainer

//DataTables
HtmlDropDownListWithTwoInputsNameOnlyFill
HtmlDropDownListWithInputNameOnlyFill
ParamStationsFromSiteIdSecGet

//Param
ParamListDisplay
ParamGetStations
ParamGetStations

CertLaneIsCamContextSwitch
CertLaneIsCamIapiSwitch



//Topbar
TopBarFixHomeDisplay
TopBarFixDisplay
TopBarFixGet
TopBarFixFormGet
TopBarFixHomeFormGet
TopBarFixAdd
TopBarFixEdit
TopBarLogGet
TopBarLogFormGet
TopBarConnGet
TopBarFixEdit
TopBarNotifGet
TopBarNotiRead
TopBarLogCountGet

//Collab
CollabCalendarOpen

RightBarHide
RightBarShow
LeftBarHide
LeftBarShow

CollabHomeOpen
CollabPresetGet
CollabAppsGet
CollabModulesGet
CollabPluginsGet
CollabPluginsXorGet
CollabPluginsXorGet(0, 'Fix');

CollabActionTourGet

CollabDemandOpen
CollabDemandAdd

CollabMonitorOpen

CollabInfoOpen

CollabAppsGet
CollabBugOpen
CollabBugAdd
CollabActionDisplay
CollabActionSearch
CollabActionGet
CollabActionFormLoad
CollabActionEdit
CollabActionImageGet
CollabActionProfilGet
CollabActionReset
CollabDetailGet
CollabPresetGet

CollabTeamOpen
CollabTeamDisplay
CollabTeamGet
CollabTeamAdd
CollabTeamInsert
CollabTeamFormLoad
CollabTeamFormOnClickGet

CollabMemberOpen
CollabTeamMembersDelete
Collabteam
CollabActionNotify
CollabActionEdit
CollabActionComment
CollabTaskTeamsDelete

CollabAdminOpen
CollabAdminDisplay
CollabAdminMemberDisplay
CollabAdminMemberGet
CollabAdminMemberAdd
CollabAdminMemberDelete
CommonUsersGet

CollabModulesGet
CollabPluginsGet
//Project
ProjectAllReportsHide
ProjectAllParametersHide
ProjectHomeOpen

ProjectManCostOpen
ProjectManCostDisplay
ProjectManCostGet
ProjectManCostAdd

ProjectAdminOpen
ProjectAdminDisplay

ProjectAdminProjectAdd
ProjectAdminProjectDisplay
ProjectAdminProjectGet

ProjectAdminZoneDisplay
ProjectAdminZoneGet
ProjectAdminZoneAdd

ProjectAdminBuildingDisplay
ProjectAdminBuildingGet
ProjectAdminBuildingAdd


ProjectAdminStageDisplay
ProjectAdminStageGet
ProjectAdminStageAdd

ProjectAdminCompanyDisplay
ProjectAdminCompanyGet
ProjectAdminCompanyAdd

ProjectAdminSponsorDisplay
ProjectAdminSponsorGet
ProjectAdminSponsorAdd

ProjectAdminProjectManagerDisplay
ProjectAdminProjectManagerGet
ProjectAdminProjectManagerAdd

ProjectAdminProjectFunctionDisplay
ProjectAdminProjectFunctionGet
ProjectAdminProjectFunctionAdd

NotiConnectionIdGet
CertImageHomeOpen

//Asset
AssetAllReportsHide
AssetAllParametersHide
AssetHomeOpen

ProjectManCostOpen
ProjectManCostDisplay
ProjectManCostGet



//RepoTrafic
RepoTraficStationHourDisplay
RepoTraficStationHourGet
RepoTraficStationHomeOpen
RepoTraficStationHourOpen
RepoTraficStationHourClOpeUpload

RepoTraficStationDayAllOpen
RepoTraficRevenueStationDayAllMeNotify
RepoTraficRevenueStationDayAllRegionNotify
RepoTraficRevenueStationDayAllDgNotify

RepoTraficRevenueMeanValueUpdate
RepoTraficStationHourMeanValueUpdate


RepoTraficOdAxleDayAllGet

UpdateNoti

CollabActionEdit
TraficStationAllGet
//Certification

CertTrxLaneSpecificBillingIdAllSearch
CertCtrDetailGet
CertTrxLaneLaneGet
CertCtrTrxLaneSearch
CertCtrTrxBillingIdSearch
CertTrxLaneStationSearch
CertTrxLaneStationGet
CertTrxLaneLaneSearch

CertTrxLaneGet

CertTaskVisualizeMsgGet
DataTableGetContact


CertDayDisplay

//CertInterface
CertInterfaceOpen
CertInterfaceAllDisplay
CertInterfaceDayDisplay
CertInterfaceDayGet
CertInterfaceStationDisplay
CertInterfaceStationSearch
CertInterfaceStationGet
CertStationDelete

CertBreachOpen
CertBreachAllDisplay
CertBreachDayDisplay
CertBreachDayGet
CertBreachStationDisplay
CertBreachStationSearch
CertBreachStationGet
CertBreachLaneDisplay
CertBreachLaneSearch
CertBreachLaneGet
CertBreachSearch
CertEventGet
//CertImage
CertImageTrxLaneSearch
CertImageTrxLaneGet
CertImageLaneOpen
CertImageLaneDayDisplay
CertImageLaneDayGet
CertImageLaneStationDisplay
CertImageLaneStationSearch
CertImageLaneStationGet
CertImageLaneLaneDisplay
CertImageLaneLaneSearch
CertImageLaneLaneGet
CertImageLaneHourGet




//Collab
GetDigits
TopBarFixAdd
TopBarFixDisplay
TopBarFixSearch
TopBarFixGet
TopBarFixEdit
TopBarFixRead
TopBarConnGet
TopBarChatGet
TopBarChatFormGet
TopBarChatMsgGet
TopBarChatMsgFormGet
TopBarChatMsgSend
TopBarChatMsgGet
TopBarChatCountGet
TopBarChatContCountGet
TopBarConnGet
TopBarUserImageSrcGet
ContChatSearch
ContChatMessagesGet
DataTableMessageGet

chatMessageSendNotify
CertLaneCtrUpload

CertTrxLaneStationGet

CertTaskAdd
CertUpdate
CertLaneCtrUpdate
CertCtrDetailUpdate


CertImageUpload
ParamLSFromRegionSecGet
ParamAxlesFromRegionSecGet



RepoManagerReportGet
RepoManagerReportAdd
RepoManagerReportNotify
RepoManagerReportExport

ParamCashiersGet
ParamStationsFromCellGet
ParamLanesAllFromStationCellGet
ParamLSFromRegionSecXorGet
ParamCellsFromRegionSecXorGet

//RepoSpc

RepoSpcEditBreakAdd
RepoSpcHomeOpen
RepoSpcReportOpen
RepoSpcReportDisplay
RepoSpcReportGet
RepoSpcReportEdit
RepoSpcReportFormLoad
RepoSpcReportAdd
RepoSpcReportNotify
RepoSpcReportExport

RepoSpcAffectHomeOpen
RepoSpcAffOpen
RepoSpcAffDisplay
RepoSpcAffGet
RepoSpcAffAdd
RepoSpcAffInsert
RepoSpcAffDelete
RepoSpcAffExport

RepoSpcEventHomeOpen
RepoSpcEventOpen
RepoSpcEventDisplay
RepoSpcEventGet
RepoSpcEventAdd
RepoSpcEventInsert
RepoSpcEventDelete

RepoSpcGapOpen
RepoSpcGapDisplay
RepoSpcGapGet
RepoSpcGapAdd
RepoSpcGapInsert

RepoSpcBreakOpen
RepoSpcBreakDisplay
RepoSpcBreakGet
RepoSpcBreakAdd
RepoSpcBreakInsert

RepoSpcNoteOpen
RepoSpcNoteDisplay
RepoSpcNoteGet
RepoSpcNoteAdd
RepoSpcNoteInsert

RepoManagerNoteAdd
RepoSpcNoteInsert
RepoSpcNoteGet

RepoManagerReportDisplay
RepoManagerReportGet
RepoManagerReportNotify

RepoSpcPerfDisplay
RepoSpcPerfOpen

QualifPathFormLoad


RabbitQueueCountCheck

CertStationDelete
CertInterfaceStationGet





CertImageTrxLaneGet

CertImageTrxBorneSearch
CertImageTrxBorneGet

CertTrxLaneStationDisplay
CertTrxLaneStationGet

CertFileHomeOpen
CertFileDayVisualize
CertFileUpdateAdd
CertFileCeLaneExport

CertFileZipDownload
CertFileZipVisualize

//Chargement
CertFileMsgDownload
CertTaskAdd

CertFileManOpen
CertFileManDisplay
CertFileManAdd
CertFileManDelete
CertFileManRestart();
CertFileRestart


CertFileAutoOpen
CertFileAutoDisplay
CertFileAutoAdd
CertFileAddDisplay

CertFilePlay

CertFileAutoRestart



CertFileAddDisplay
CertFilePlanDelete

CertFileLogsDownload
CertTaskVisualizeLogsGet
CertFileLogsDelete
CertFilevis

CertFileAutoOpen
CertFilePlay

CertFilePlan
CertFilePlanDisplay
CertFilePlanRecover

CertFilePlanOpen
CertFilePlanDisplay
CertFileAutoDisplay
CertFilePlanDelete
CertFilePlanAllPlay
CertFileUpdateAdd

//MaintMenu
MaintConfigAllReportsHide
MaintConfigAllParametersHide

MaintPathDisplay
MaintHomeOpen

MaintConfigHomeOpen

MaintFeaturesOpen
MaintFeaturesDisplay
MaintFeaturesGet

MaintPathOpen
MaintPathDisplay
MaintPathGet

MaintTollPriceOpen
MaintTollPriceDisplay
MaintTollPriceGet

MaintEventHomeOpen
MaintEventOpen
MaintEventPresetGet

MainEventAllDisplay

MaintEventEquipmentRegionDisplay
MaintEventEquipmentRegionSearch
MaintEventEquipmentRegionGet

MaintEventEquipmentAxleDayDisplay
MaintEventEquipmentAxleDaySearch
MaintEventEquipmentAxleDayGet


MaintEventScopeCumulOpen
MaintEventEquipmentScopeCumulDisplay
MaintEventEquipmentScopeCumulSearch
MaintEventEquipmentScopeCumulGet

MaintEventScopeDayOpen
MaintEventEquipmentScopeDayDisplay
MaintEventEquipmentScopeDaySearch
MaintEventEquipmentScopeDayGet
MaintEventEquipmentScopeDayFromScopeCumulSearch

MaintEventEquipmentStationCumulDisplay
MaintEventEquipmentStationCumulSearch
MaintEventEquipmentStationCumulGet
MaintEventEquipmentStationCumulFromScopeCumulSearch

MaintEventEquipmentStationDayDisplay
MaintEventEquipmentStationDaySearch
MaintEventEquipmentStationDayGet
MaintEventEquipmentStationDayFromScopeSearch
MaintEventEquipmentStationDayFromStationCumulSearch

MaintEventEquipmentLaneCumulOpen
MaintEventEquipmentLaneCumulDisplay
MaintEventEquipmentLaneCumulSearch
MaintEventEquipmentLaneCumulGet
MaintEventEquipmentLaneCumulFromStationCumulSearch
MaintEventEquipmentLaneCumulFromScopeCumulSearch

MaintEventEquipmentLaneDayOpen
MaintEventEquipmentLaneDayDisplay
MaintEventEquipmentLaneDaySearch
MaintEventEquipmentLaneDayGet
MaintEventEquipmentLaneDayFromLaneCumulSearch
MaintEventEquipmentLaneDayFromScopeDaySearch

MaintEventDayOpen

MaintEventSearch
MaintEventGet


ParamEventGet

MaintFeaturesDisplay
MaintFeaturesGet
MaintEventGet





MaintPingOpen
MaintPingDisplay
MaintPingGet
MaintPingTest

MaintCameraOpen
MaintCameraDisplay
MaintCameraGet

MaintBreakOpen
MaintBreakDisplay
MaintBreakGet

MaintDispo
MaintDiHomeOpen



MaintEventHomeOpen
MaintEventDayOpen









DataTableBooleanFalseAlertGet
//Param
ParamItemCategoriesGet
ParamStationsFromLSGet
ParamStationsFromCellGet
ParamStationsFromLSSecGet
ParamStationsFromLSGet
ParamStationsGet
ParamLSFromRegionSecGet
ParamLSFromRegionSecXorGet
ParamCellsFromRegionSecXorGet
ParamLanesAllFromStationLSGet
ParamLanesAllFromStationCellGet
ParamCellsFromRegionSecGet
ParamStationsFromRegionSecGet
ParamCashiersGet
ParamCashiersFromCellGet
ParamUsersGet
ParamLanesFromStationLSGet
ParamLanesFromStationLSGet
ParamLanesFromStationLS
ParamLanesAllFromStationLSSensGet
ParamCexSecGet
ParamLSSecGet

CertUpdate
CertPostCexGet
CertPostStationOpen
CertLaneCtrUpload


//Versionning
CommVersVersionOpen
CommVersHomeOpen
CommVersionNotify
CommVersionGet
CommVersionExport
CommReleaseDisplay
CommReleaseGet
ParamVersVersionGet



QualifTimePreset

//Param
ParamLanesLaneGet
ParamTimesGet
ParamLanesFromStationLSGet
ParamStationsGet

//Admin
AdminAllReportsHide
AdminAllParametersHide
AdminHomeOpen

AdminUserInfosOpen
AdminUserInfosDisplay
AdminUserInfosGet
AdminUserInfosAdd
AdminUserInfosInsert

AdminUserRegionsOpen
AdminUserRegionsDisplay
AdminUserRegionsGet
AdminUserRegionsAdd
AdminUserRegionsInsert
AdminUserRegionsDelete

AdminUserRoleOpen
AdminUserRolesDisplay
AdminUserRolesAdd
AdminUserRolesInsert

AdminUserLSOpen
AdminUserLSDisplay
AdminUserLSGet
AdminUserLSAdd
AdminUserLSInsert
AdminUserLSDelete

AdminUserStationOpen
AdminUserStationDisplay
AdminUserStationGet
AdminUserStationAdd
AdminUserStationInsert

AdminUserNotifOpen
AdminUserNotifDisplay
AdminUserNotifGet
AdminUserNotifAdd
AdminUserNotifInsert

AdminUserCellOpen
AdminUserCellDisplay
AdminUserCellGet
AdminUserCellAdd
AdminUserCellInsert
AdminUserCellDelete


AdminSupervisionHomeOpen
AdminServersOpen
AdminServersDisplay
AdminServersGet
AdminServerTaskRun

AdminAppsOpen
AdminAppsDisplay
AdminAppsGet

AdminAppTaskRun

AdminUserCellDisplay
AdminUserCellGet
AdminUserCellAdd
AdminUserCellInsert
AdminUserCellDelete

//ChartJs
ChartJsLineThreeTraficHourDisplay
ChartJsLineTwoOldDisplay
ParamStationsFromLSGet
ParamStationsFromCellGet